### ISSUE TITLE
Detailed Player Count view

### ISSUE THREAD

**Issue by Arcadius2006** [LittleBigRefresh/refresh-web#72] opened 2024-04-10 06:32 UTC
if you click on the "There are currently X players playing across X rooms" things, you should be brought over to a more detailed view, detailing which players are playing on which game and platform

i'm requesting this because it would make matchmaking a tad easier than it is right now

**Comment by jvyden** [comment] 2024-04-10 06:33
Duplicate of #70

**Closed by jvyden** 2024-04-10 06:33 UTC
